# More information on gocd-flavor YAML can be found here:
# - https://github.com/tomzo/gocd-yaml-config-plugin#pipeline
# - https://www.notion.so/sentry/GoCD-New-Service-Quickstart-6d8db7a6964049b3b0e78b8a4b52e25d
format_version: 10
pipelines:
    hello-world:
        group: timeseries-analysis-service
        lock_behavior: unlockWhenFinished
        materials:
            timeseries_analysis_service_repo:
                git: git@github.com:getsentry/timeseries-analysis-service.git
                shallow_clone: true
                branch: main
                destination: timeseries-analysis-service
        # A pipeline executes stages sequentially.
        stages:
            - do-stuff:
                  # Since this is the first stage,
                  # manual approval will block the pipeline from automatically
                  # being run when the materials change upstream.
                  approval:
                      type: manual
                  fetch_materials: true
                  # A stage executes jobs in parallel.
                  jobs:
                      say-hello:
                          timeout: 600 # 10 minutes
                          elastic_profile_id: timeseries-analysis-service
                          # A job executes tasks sequentially.
                          tasks:
                              - script: |
                                  echo "hello..."
                              - script: |
                                  echo "world!"
                      list-files:
                          timeout: 1800 # 30 mins
                          elastic_profile_id: timeseries-analysis-service
                          tasks:
                              # We generally recommend calling a script
                              # in your repository instead of writing
                              # multiline shell script here.
                              # See the following stage for an example.
                              - script: |
                                  cd timeseries-analysis-service
                                  ls -lah
            - do-more-stuff:
                  approval:
                      type: manual
                      # Manual approval is only enabled if the previous stage
                      # succeeded.
                      allow_only_on_success: true
                  jobs:
                      say-goodbye:
                          timeout: 600
                          elastic_profile_id: timeseries-analysis-service
                          tasks:
                              - exec:
                                  working-directory: timeseries-analysis-service
                                  # NOTE: the command needs to start with ./
                                  command: ./gocd/pipelines/demo.sh
                                  arguments:
                                  - foo
                                  - bar
